# Generated by Django 4.1.1 on 2022-09-15 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='routine_id',
            field=models.BigAutoField(db_column='routine_id', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='routine_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='routineresult',
            name='routine_result_id',
            field=models.BigAutoField(db_column='routine_result_id', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='routineresult',
            old_name='routine_result_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='routine',
            name='account',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routineday',
            name='routine',
            field=models.ForeignKey(db_column='routine_id', on_delete=django.db.models.deletion.CASCADE, to='routine.routine'),
        ),
        migrations.AlterField(
            model_name='routineresult',
            name='routine',
            field=models.ForeignKey(db_column='routine_id', on_delete=django.db.models.deletion.CASCADE, to='routine.routine'),
        ),
    ]
